/**
 * RulesGenerator — .mdc 文件生成器
 *
 * 生成 Cursor Rules 格式的 .mdc 文件到 .cursor/rules/ 目录：
 *   - Channel A: alembic-project-rules.mdc (alwaysApply: true)
 *   - Channel B: alembic-patterns-{topic}.mdc (alwaysApply: false)
 */

import fs from 'node:fs';
import path from 'node:path';
import { BUDGET, estimateTokens } from './TokenBudget.js';

export class RulesGenerator {
  projectName: string;
  projectRoot: string;
  rulesDir: string;
  /**
   * @param projectRoot 用户项目根目录
   * @param projectName 项目名称（用于 description/标题）
   */
  constructor(projectRoot: string, projectName = 'Project') {
    this.projectRoot = projectRoot;
    this.projectName = projectName;
    this.rulesDir = path.join(projectRoot, '.cursor', 'rules');
  }

  /**
   * Channel A — 写入 Always-On Rules 文件
   *
   * @param ruleLines 一行式规则列表 (来自 KnowledgeCompressor.compressToRuleLine)
   * @returns }
   */
  writeAlwaysOnRules(ruleLines: string[]) {
    this._ensureDir();

    // Token 预算控制
    const kept: string[] = [];
    let tokens = 0;
    const headerFooterBudget = 100;
    const ruleBudget = BUDGET.CHANNEL_A_MAX - headerFooterBudget;

    for (const line of ruleLines) {
      const lineTokens = estimateTokens(line);
      if (tokens + lineTokens <= ruleBudget && kept.length < BUDGET.CHANNEL_A_MAX_RULES) {
        kept.push(line);
        tokens += lineTokens;
      }
    }

    const content = this._renderChannelA(kept);
    const filePath = path.join(this.rulesDir, 'alembic-project-rules.mdc');
    fs.writeFileSync(filePath, content, 'utf8');

    return {
      filePath,
      tokensUsed: estimateTokens(content),
      rulesCount: kept.length,
    };
  }

  /**
   * Channel B — 写入 Smart Rules 文件（按主题）
   *
   * @param topic 主题名 (networking, ui, data, architecture, conventions, general)
   * @param compressedContent 格式化后的 When/Do/Don't Markdown 内容
   * @param description Agent 关联性判断用 description
   * @returns }
   */
  writeSmartRules(topic: string, compressedContent: string, description: string) {
    this._ensureDir();

    // Token 预算控制
    let body = compressedContent;
    const totalTokens = estimateTokens(body) + estimateTokens(description) + 50;
    if (totalTokens > BUDGET.CHANNEL_B_MAX_PER_FILE) {
      // 截断尾部
      const lines = body.split('\n');
      const truncated: string[] = [];
      let used = estimateTokens(description) + 50;
      for (const line of lines) {
        used += estimateTokens(`${line}\n`);
        if (used <= BUDGET.CHANNEL_B_MAX_PER_FILE) {
          truncated.push(line);
        }
      }
      body = truncated.join('\n');
    }

    const content = this._renderChannelB(topic, body, description);
    const fileName = `alembic-patterns-${topic}.mdc`;
    const filePath = path.join(this.rulesDir, fileName);
    fs.writeFileSync(filePath, content, 'utf8');

    return {
      filePath,
      tokensUsed: estimateTokens(content),
    };
  }

  /**
   * 清理旧的动态生成文件
   * 保留静态模板文件（alembic-conventions.mdc, alembic-skills.mdc）
   */
  cleanDynamicFiles() {
    if (!fs.existsSync(this.rulesDir)) {
      return;
    }

    const dynamicPrefixes = ['alembic-project-rules', 'alembic-patterns-'];
    const files = fs.readdirSync(this.rulesDir);
    for (const file of files) {
      if (dynamicPrefixes.some((p) => file.startsWith(p))) {
        const filePath = path.join(this.rulesDir, file);
        try {
          fs.unlinkSync(filePath);
        } catch {
          /* ignore */
        }
      }
    }
  }

  // ─── 渲染方法 ───────────────────────────────────────

  _renderChannelA(ruleLines: string[]) {
    const desc = `${this.projectName} mandatory rules — coding constraints that must never be violated. Auto-generated by Alembic.`;
    const lines = [
      '---',
      `description: "${desc}"`,
      'alwaysApply: true',
      '---',
      '',
      `# ${this.projectName} — Mandatory Rules`,
      '',
      ...ruleLines,
      '',
      'For detailed patterns and recipes, Alembic MCP tools are available:',
      '- `asd_search({ query })` — search knowledge base (auto mode: BM25 + semantic)',
      '- `asd_search({ query, mode: "context" })` — context-aware search with history',
    ];
    return `${lines.join('\n')}\n`;
  }

  _renderChannelB(topic: string, body: string, description: string) {
    const topicLabel = topic.charAt(0).toUpperCase() + topic.slice(1);
    const lines = [
      '---',
      `description: "${description}"`,
      'alwaysApply: false',
      '---',
      '',
      `# ${topicLabel} Patterns`,
      '',
      body,
      '',
      `For full code examples: \`asd_search("${topic}")\``,
    ];
    return `${lines.join('\n')}\n`;
  }

  /**
   * Baseline Rules — 零知识库时写入基础引导文件
   * 告知 Agent 可用的 MCP 工具和推荐工作流
   */
  writeBaselineRules() {
    this._ensureDir();

    const content = this._renderBaseline();
    const filePath = path.join(this.rulesDir, 'alembic-project-rules.mdc');
    fs.writeFileSync(filePath, content, 'utf8');

    return {
      filePath,
      tokensUsed: estimateTokens(content),
      rulesCount: 0,
    };
  }

  _renderBaseline() {
    const lines = [
      '---',
      `description: "${this.projectName} — Alembic baseline guidance. Available MCP tools and recommended workflows."`,
      'alwaysApply: true',
      '---',
      '',
      `# ${this.projectName} — Alembic Baseline`,
      '',
      'This project has Alembic enabled but no knowledge entries yet.',
      'Use the following MCP tools to build and query the knowledge base:',
      '',
      '## Available MCP Tools',
      '',
      '- `asd_bootstrap` — Cold-start: analyze the project and generate initial knowledge entries',
      '- `asd_search({ query })` — Search knowledge base (BM25 + semantic)',
      '- `asd_submit_knowledge` — Submit a knowledge candidate (strict validation)',
      '- `asd_guard` — Run compliance review on current changes',
      '- `asd_task` — Task & decision management (prime/create/claim/close/record_decision)',
      '- `asd_panorama` — Project panorama (overview/module/gaps/health)',
      '',
      '## Recommended First Steps',
      '',
      '1. Run `asd_bootstrap` to analyze the codebase and generate initial recipes',
      '2. Use `asd_search` to query knowledge while coding',
      '3. Run `asd_guard` before committing to check compliance',
    ];
    return `${lines.join('\n')}\n`;
  }

  _ensureDir() {
    if (!fs.existsSync(this.rulesDir)) {
      fs.mkdirSync(this.rulesDir, { recursive: true });
    }
  }
}

export default RulesGenerator;
