/**
 * mergeSection — 四种合并场景单元测试
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mergeSection } from '../../lib/service/delivery/FileProtection.js';

describe('mergeSection', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mergeSection-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  const header = '# Test Project — Agent Instructions\n\n> Auto-generated by Alembic.\n';
  const section = '## Coding Standards\n\n- Rule 1\n- Rule 2\n';
  const logger = { info: () => {} };

  // ─── Case 1: 文件不存在 → 创建 ─────────────────────

  it('Case 1: creates new file with header + markers when file does not exist', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');

    const result = mergeSection(filePath, section, { header, logger });

    expect(result.written).toBe(true);
    expect(result.strategy).toBe('create');

    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('# Test Project — Agent Instructions');
    expect(content).toContain('<!-- asd:begin -->');
    expect(content).toContain('## Coding Standards');
    expect(content).toContain('<!-- asd:end -->');
  });

  it('Case 1: creates parent directory if needed', () => {
    const filePath = path.join(tmpDir, '.github', 'copilot-instructions.md');

    mergeSection(filePath, section, { logger });

    expect(fs.existsSync(filePath)).toBe(true);
  });

  it('Case 1: works without header (copilot-instructions style)', () => {
    const filePath = path.join(tmpDir, 'copilot.md');
    const sectionWithMarkers = '<!-- asd:begin -->\n\n# Alembic Conventions\n\n<!-- asd:end -->';

    const result = mergeSection(filePath, sectionWithMarkers, { logger });

    expect(result.strategy).toBe('create');
    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('<!-- asd:begin -->');
    expect(content).not.toContain('undefined');
  });

  // ─── Case 2: 有 markers → 替换区段 ─────────────────

  it('Case 2: replaces marker section in existing file, preserving user content', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const existingContent = [
      '# My Project Guidelines',
      '',
      '## Custom Architecture Notes',
      'User-written content here.',
      '',
      '<!-- asd:begin -->',
      '## Old Coding Standards',
      '- Old rule',
      '<!-- asd:end -->',
      '',
    ].join('\n');
    fs.writeFileSync(filePath, existingContent);

    const result = mergeSection(filePath, '## New Standards\n\n- New rule\n', { header, logger });

    expect(result.written).toBe(true);
    expect(result.strategy).toBe('replace-section');

    const content = fs.readFileSync(filePath, 'utf8');
    // User content preserved
    expect(content).toContain('# My Project Guidelines');
    expect(content).toContain('User-written content here.');
    // Old section replaced
    expect(content).not.toContain('Old rule');
    // New section present
    expect(content).toContain('## New Standards');
    expect(content).toContain('- New rule');
    expect(content).toContain('<!-- asd:begin -->');
    expect(content).toContain('<!-- asd:end -->');
  });

  it('Case 2: skips write when section content is unchanged', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const markerContent = '<!-- asd:begin -->\n\n## Same\n\n<!-- asd:end -->';
    fs.writeFileSync(filePath, `User header\n\n${markerContent}\n`);

    const result = mergeSection(filePath, markerContent, { logger });

    expect(result.written).toBe(false);
    expect(result.strategy).toBe('replace-section');
  });

  // ─── Case 3: 旧版 Alembic 文件 → 重写加标记 ────

  it('Case 3: rewrites legacy Alembic file with markers', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const legacyContent = [
      '# Project — Agent Instructions',
      '',
      '> Auto-generated by [Alembic](https://github.com/GxFn/Alembic). Do not edit manually.',
      '',
      '## Old Coding Standards',
      '- Old rule from legacy',
      '',
    ].join('\n');
    fs.writeFileSync(filePath, legacyContent);

    const result = mergeSection(filePath, section, { header, logger });

    expect(result.written).toBe(true);
    expect(result.strategy).toBe('rewrite-legacy');

    const content = fs.readFileSync(filePath, 'utf8');
    // Header rewritten
    expect(content).toContain('# Test Project — Agent Instructions');
    // Markers added
    expect(content).toContain('<!-- asd:begin -->');
    expect(content).toContain('<!-- asd:end -->');
    // New section content
    expect(content).toContain('## Coding Standards');
    // Old content gone
    expect(content).not.toContain('Old rule from legacy');
  });

  // ─── Case 4: 用户文件 → 追加区段 ────────────────────

  it('Case 4: appends marker section to user-owned file', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const userContent = [
      '# Project Guidelines',
      '',
      '## Architecture',
      'MVVM + Repository pattern.',
      '',
      '## Code Style',
      'Use Input/Output pattern.',
      '',
    ].join('\n');
    fs.writeFileSync(filePath, userContent);

    const result = mergeSection(filePath, section, { header, logger });

    expect(result.written).toBe(true);
    expect(result.strategy).toBe('append-section');

    const content = fs.readFileSync(filePath, 'utf8');
    // User content preserved at top
    expect(content).toContain('# Project Guidelines');
    expect(content).toContain('MVVM + Repository pattern.');
    expect(content).toContain('Use Input/Output pattern.');
    // Alembic section appended
    expect(content).toContain('<!-- asd:begin -->');
    expect(content).toContain('## Coding Standards');
    expect(content).toContain('<!-- asd:end -->');
    // Header NOT injected (user already has their own header)
    expect(content).not.toContain('Auto-generated by Alembic');
  });

  it('Case 4: subsequent runs use Case 2 (replace-section) after initial append', () => {
    const filePath = path.join(tmpDir, 'AGENTS.md');
    const userContent = '# User Project\n\nUser notes.\n';
    fs.writeFileSync(filePath, userContent);

    // First run: append
    const r1 = mergeSection(filePath, '## V1 Rules\n- Rule A\n', { logger });
    expect(r1.strategy).toBe('append-section');

    // Second run: replace-section (markers now exist)
    const r2 = mergeSection(filePath, '## V2 Rules\n- Rule B\n', { logger });
    expect(r2.strategy).toBe('replace-section');

    const content = fs.readFileSync(filePath, 'utf8');
    expect(content).toContain('# User Project');
    expect(content).toContain('User notes.');
    expect(content).not.toContain('Rule A'); // V1 replaced
    expect(content).toContain('Rule B'); // V2 present
  });
});
